version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: sonar-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - pgsonar:/var/lib/postgresql/data
    networks:
      - sonarnet

  sonarqube:
    image: sonarqube:10-community
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonardata:/opt/sonarqube/data
      - sonarlogs:/opt/sonarqube/logs
      - sonarext:/opt/sonarqube/extensions
    networks:
      - sonarnet

volumes:
  pgsonar:
  sonardata:
  sonarlogs:
  sonarext:

networks:
  sonarnet: